# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - '.github/workflows/scala.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/scala.yml'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Set up sbt launcher
      uses: sbt/setup-sbt@v1
    - name: Compile
      working-directory: ./backend/pangolin-backend
      run: sbt compile
    - name: Run tests
      working-directory: ./backend/pangolin-backend
      run: sbt test
